services:
  nginx:
    image: nginx:latest
    container_name: nginx_static
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./:/var/www/html
    # ports:
    #   - "80:80"
    restart: always
